CREATE TABLE TICKETS(
    TICKETS_ID VARCHAR(255) NOT NULL,
    TICKETS_CATEGORY VARCHAR(255),
    TICKETS_CLIENTE VARCHAR(255),
    TICKETS_TECNICO VARCHAR(255),
    TICKETS_DATE DATE,
    TICKETS_DESCRICAO VARCHAR(255),
    TICKETS_STATUS VARCHAR(255),
    TICKETS_PRIORITY VARCHAR(255));

CREATE TABLE CATEGORY(
    CATEGORY_ID VARCHAR(255) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(255));

CREATE TABLE CLIENT(
    CLIENT_ID VARCHAR(255) NOT NULL,
    CLIENT_CPF VARCHAR(18),
    CLIENT_LOGIN VARCHAR(20),
    CLIENT_PASSWORD VARCHAR(20),
    CLIENT_NAME VARCHAR(255),
    CLIENT_EMAIL VARCHAR(255),
    CLIENT_DATE VARCHAR(10),
    CLIENT_CONTACT VARCHAR(16),
    CLIENT_LOG VARCHAR(255),
    CLIENT_NEIGH VARCHAR(255),
    CLIENT_NUMBER VARCHAR(255),
    CLIENT_ZIP VARCHAR(9),
    CLIENT_CITY VARCHAR(255),
    CLIENT_STATE VARCHAR(2));

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID VARCHAR(255) NOT NULL,
    EMPLOYEE_CPF VARCHAR(14),
    EMPLOYEE_LOGIN VARCHAR(20),
    EMPLOYEE_PASSWORD VARCHAR(20),
    EMPLOYEE_NAME VARCHAR(255),
    EMPLOYEE_EMAIL VARCHAR(255),
    EMPLOYEE_DATE DATE,
    EMPLOYEE_CONTACT VARCHAR(16),
    EMPLOYEE_LOG VARCHAR(255),
    EMPLOYEE_NEIGH VARCHAR(255),
    EMPLOYEE_NUMBER INT,
    EMPLOYEE_ZIP VARCHAR(9),
    EMPLOYEE_CITY VARCHAR(255),
    EMPLOYEE_STATE VARCHAR(2));

